import json
import os
import time
from preprocessing import TextPreprocessor
from llm_extraction import LLMExtractor
from embeddings import EmbeddingGenerator

class ProcessingPipeline:
    def __init__(self):
        self.preprocessor = TextPreprocessor()
        self.llm_extractor = LLMExtractor()
        self.embedding_generator = EmbeddingGenerator()

    def run(self, input_file: str, output_file: str):
        print("=== Starting AI Processing Pipeline (Phase 3) ===")
        if not os.path.exists(input_file):
            print(f"Error: {input_file} not found. Please run Phase 2 Ingestion first.")
            return

        with open(input_file, 'r', encoding='utf-8') as f:
            reviews = json.load(f)

        print(f"Loaded {len(reviews)} raw reviews. Processing...")
        enriched_reviews = []

        # Process a subset or all, but let's process them all sequentially with a slight delay
        for i, review in enumerate(reviews):
            text = review.get("content", "")
            
            # 1. Preprocessing & Language Detection
            lang = self.preprocessor.detect_language(text)
            clean_txt = self.preprocessor.clean_text(text)
            
            # We only process English/Unknown reviews for this initial AI pass
            if lang not in ["en", "unknown"]:
                review["processing_status"] = "skipped_non_english"
                enriched_reviews.append(review)
                continue

            # Skip very short reviews
            if len(clean_txt.strip()) < 20:
                review["processing_status"] = "skipped_too_short"
                enriched_reviews.append(review)
                continue
                
            # 2. LLM Intent Extraction (now doing sentiment and segment too)
            # Add a small delay to avoid hitting RPM limits on Groq free tier
            time.sleep(0.5)
            
            insights = self.llm_extractor.extract_insights(review)
            
            if insights:
                review["claude_output"] = insights # Store it under claude_output to match Dashboard UI expectations
                review["sentiment"] = insights.get("sentiment", "neutral").upper()
                review["user_segment"] = insights.get("user_segment", "general_user")
            else:
                review["claude_output"] = None
                review["sentiment"] = "NEUTRAL"
                review["user_segment"] = "General User"

            # 3. Generate Embedding for Vector Search
            embedding = self.embedding_generator.generate_embedding(clean_txt)
            review["embedding"] = embedding
            review["processing_status"] = "completed"

            enriched_reviews.append(review)

            if (i + 1) % 50 == 0:
                print(f"Processed {i + 1}/{len(reviews)} reviews...")
                # Write intermediate progress
                with open(output_file, 'w', encoding='utf-8') as f:
                    json.dump(enriched_reviews, f, indent=2)

        # 5. Save the final enriched data
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(enriched_reviews, f, indent=2)
        
        print(f"=== Pipeline Complete. {len(enriched_reviews)} reviews enriched. ===")
        print(f"Data saved to {output_file}")

if __name__ == "__main__":
    pipeline = ProcessingPipeline()
    # Read the JSON generated by Phase 2, and output the Phase 3 JSON
    input_path = os.path.join(os.path.dirname(__file__), "..", "ingestion", "raw_reviews_dump.json")
    output_path = os.path.join(os.path.dirname(__file__), "enriched_reviews.json")
    pipeline.run(input_file=input_path, output_file=output_path)
