import json
import os
from preprocessing import TextPreprocessor
from analyzer import SentimentAnalyzer, SegmentClassifier
from llm_extraction import LLMExtractor
from embeddings import EmbeddingGenerator

class ProcessingPipeline:
    def __init__(self):
        self.preprocessor = TextPreprocessor()
        self.sentiment_analyzer = SentimentAnalyzer()
        self.segment_classifier = SegmentClassifier()
        self.llm_extractor = LLMExtractor()
        self.embedding_generator = EmbeddingGenerator()

    def run(self, input_file: str, output_file: str):
        print("=== Starting AI Processing Pipeline (Phase 3) ===")
        if not os.path.exists(input_file):
            print(f"Error: {input_file} not found. Please run Phase 2 Ingestion first.")
            return

        with open(input_file, 'r', encoding='utf-8') as f:
            reviews = json.load(f)

        print(f"Loaded {len(reviews)} raw reviews. Processing...")
        enriched_reviews = []

        for i, review in enumerate(reviews):
            text = review.get("content", "")
            
            # 1. Preprocessing & Language Detection
            lang = self.preprocessor.detect_language(text)
            clean_txt = self.preprocessor.clean_text(text)
            
            # We only process English reviews for this initial AI pass
            if lang != "en" and lang != "unknown":
                review["processing_status"] = "skipped_non_english"
                enriched_reviews.append(review)
                continue

            # 2. Core Analysis (Sentiment & Segment)
            sentiment_data = self.sentiment_analyzer.analyze(clean_txt)
            segment = self.segment_classifier.classify(clean_txt)
            
            # 3. LLM Intent Extraction 
            # Smart Token Saving: We only send reviews to GPT-4o if they are NEGATIVE or from a Discovery Seeker!
            insights = {}
            if segment == "Discovery Seeker" or sentiment_data["sentiment"] == "NEGATIVE":
                 insights = self.llm_extractor.extract_insights(clean_txt)

            # 4. Generate Embedding for Vector Search
            embedding = self.embedding_generator.generate_embedding(clean_txt)
            
            # 5. Enrich the original review JSON
            review["sentiment"] = sentiment_data["sentiment"]
            review["sentiment_score"] = sentiment_data["score"]
            review["user_segment"] = segment
            review["llm_insights"] = insights
            review["embedding"] = embedding
            review["processing_status"] = "completed"

            enriched_reviews.append(review)

            if (i + 1) % 200 == 0:
                print(f"Processed {i + 1}/{len(reviews)} reviews...")

        # 5. Save the enriched data
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(enriched_reviews, f, indent=2)
        
        print(f"=== Pipeline Complete. {len(enriched_reviews)} reviews enriched. ===")
        print(f"Data saved to {output_file}")

if __name__ == "__main__":
    pipeline = ProcessingPipeline()
    # Read the JSON generated by Phase 2, and output the Phase 3 JSON
    input_path = os.path.join(os.path.dirname(__file__), "..", "ingestion", "raw_reviews_dump.json")
    output_path = os.path.join(os.path.dirname(__file__), "enriched_reviews.json")
    pipeline.run(input_file=input_path, output_file=output_path)
